== Rutinas de validación de la calidad de los datos

A partir del uso de <<sect-4,servicios externos>> o archivos externos, y la posibilidad que ofrece OpenRefine de <<sect-2.5.2. guardar y rehacer pasos>> es posible crear rutinas para ejecutar de manera automática varias acciones de validación de calidad. 

Aprovechando las múltiples herramientas de calidad de datos ya existentes en la red de GBIF es posible abordar de manera semi-automatizada a través de OpenRefine los retos y problemas más comúnes de calidad que se presentan a nivel taxonómico y geográfico en un conjunto de datos. Acá se presentan diferentes rutinas que validan la calidad de los datos contrastando un conjunto de datos contra dichos servicios externos y agilizan la obtención de resultados a la vez que procuran una metodología de validación replicable.

=== ¿Cómo funcionan las rutinas?

Las rutinas comparan la información documentada en el conjunto de datos contra diferentes fuentes de referencia, y a partir de dicha comparación crean columnas de validación donde se puede identificar la correspondencia entre el archivo original y la fuente de referencia a través de operadores lógicos que generan unos (1) y ceros (0) como indicadores de validación (Figura 2.).

Los *indicadores de validación* se interpretan así:

* 0: El valor documentado en el conjunto de datos NO coincide con la fuente de referencia, el valor debe ser revisado y ajustado en caso de ser necesario.
* 1: El valor documentado en el conjunto de datos coincide con la fuente de referencia, no es necesario tomar acciones adicionales.

Las rutinas utilizan como fuentes de validación (1) API’s (Interfaces de Programación de Aplicaciones) de repositorios globales taxonómicos y geográficos; y (2) archivos de texto plano obtenidos como resultado de herramientas de validación externas y  fuentes nacionales oficiales. Se explica a continuación cada fuente:

Las rutinas cuya fuente de referencia es un API, hacen una consulta  a un <<sect-4,servicio externo>> y extraen la información necesaria para hacer la validación, esta se obtiene en formato JSON y es interpretada por la rutina para hacer la información legible dentro del conjunto de datos. Posteriormente el resultado de la consulta al API es comparado con el valor documentado en el conjunto de datos y se generan nuevas columnas con los indicadores de la validación.
Las rutinas que usan como fuente archivos de texto plano, hacen una consulta sobre un archivo cargado previamente en OpenRefine, que posteriormente es comparado con el valor documentado en el conjunto de datos, como resultado de la comparación se generan nuevas columnas con los indicadores de la validación.

Acá encontrará x rutinas de limpieza (Tabla 2), teniendo en cuenta diferentes escenarios al momento de realizar la validación, como la caída temporal de servicios web, o requisitos adicionales según la naturaleza de los datos, como por ejemplo el grupo biológico de interés. Cada rutina cuenta con una descripción en la sección inicial que detalla los requerimientos para su ejecución y su funcionamiento en los idiomas inglés y español.

[#table-scripts]
.Lista de rutinas para la validación de datos primarios sobre biodiversidad
[cols=3*,options="header"]
|===
| Nombre | Enlace | Requerimientos 
| Validación taxonómica con el API de GBIF | ValTaxonomicAPIGBIF_ValTaxonomicaAPIGBIF.txt  | Require acceso a internet para hacer la petición a una API
| Validación taxonómica con Species Match de GBIF | ValTaxonomicSpeciesMatchGBIF_ValTaxonomicaSpeciesMatchGBIF.txt | Requiere que un archivo sea previamente cargado en OpenRefine para la ejecución de la rutina.
| Validación taxonómica con el API de WoRMS (World Register of Marine Species) | ValTaxonomicAPIWoRMS_ValTaxonomicaAPIWoRMS.txt | Require acceso a internet para hacer la petición a una API
| Validación de elevaciones con GeoNames | ValElevationAPIGeoNames_ValElevacionAPIGeoNames.txt | Require acceso a internet para hacer la petición a una API
|===



==== Pasos generales para correr las rutinas

Todas las rutinas se ejecutan de manera similar, los requerimientos específicos se encuentran documentados en cada rutina. En esta sección se presentan instrucciones generales para su ejecución en OpenRefine:
 
****
[discrete]
=== Paso 1

*Carga de los archivos a OpenRefine*

Cree un nuevo proyecto en OpenRefine con el conjunto de datos que desea validar, si tiene dudas sobre cómo hacerlo revise la <<sect-1, sección 1>>. Asegúrese que el conjunto de datos o los elementos que desea validar estén estructurados en el estándar Darwin Core, si no lo están ajuste el nombre de cada columna según el estándar siguiendo las instrucciones de la << sect-2.1.1, sección 2.1.1>>.

Cargue en OpenRefine archivos adicionales si la rutina lo requiere (ver <<table-scripts,Tabla 1.>>), de lo contrario vaya directamente al paso 2.
****

****
[discrete]
=== Paso 2

*Seleccionar y copiar la rutina*

Ubiqué la rutina de interés según la validación que desee realizar (ver <<table-scripts,Tabla 1.>>), revise las instrucciones y requerimientos al inicio para ejecutar la rutina  de interes y verifique que su conjunto de datos cumple todas las condiciones.

Copie el texto de la rutina de validación. Asegúrese de seleccionar todos  los corchetes iniciales ({) y finales (}), esto puede generar errores en la ejecución.


****

****
[discrete]
=== Paso 3

*Ejecutar la rutina*

Ubíquese en el conjunto de datos a validar en OpenRefine, diríjase al menú de arriba a la izquierda, seleccione la pestaña “Deshacer/Rehacer” y haga clic en el botón “Aplicar...”. A continuación se abrirá una ventana de texto vacía, pegue en el cuadro de texto la rutina a ejecutar y haga click en “Ejecutar Operaciones”. Si tiene dudas sobre este proceso revise la <<sect-2.5, sección 2.5>>

Espere a que finalice la ejecución de la rutina. Las rutinas que requieren hacer llamados a servicios externos, dependen de la conexión a internet, estas consultas toman un tiempo en correr que varía según el número de filas del conjunto de datos, de la velocidad de la conexión y de la memoria RAM del equipo. 

[[table-x]]
[caption="Table x. "]

El avance de la ejecución de la rutina se observa en la parte superior de la pantalla.

****

****
[discrete]
=== Paso 4

**Resultados de la validación**

Al terminar la ejecución de la rutina, nuevas columnas aparecerán en el conjunto de datos, estas columnas no pertenecen al estándar Darwin Core y puede identificarlas por su terminación:

* _Suggested_: valores sugeridos resultantes de la validación con las fuentes de referencia, dependiendo de la rutina seleccionada pueden ser sugerencias taxonómicas o geográficas.

* _Validation_: corresponden a los indicadores de validación (unos y ceros) que permiten rastrear diferencias entre el valor original y el valor sugerido, y realizar posteriormente una limpieza de los datos. 

****
