[[guía-de-uso-básico-de-openrefine]]
Guía de Uso Básico de OpenRefine
--------------------------------

*_Suggested citation:_*
Zermoglio PF, Wieczorek JR. 2019. Guía de Uso Básico de OpenRefine para la limpieza de datos sobre biodiversidad. Versión 3.0-ES. Available online at #foo. doi:xxxxxx

*_Persistent URI:_*
#foo

*_Authors:_*
Paula F Zermoglio and John Wieczorek (VertNet) are authors of original version and of this version of document.

*_Contributors:_*


*_License:_* "Guía de Uso Básico de OpenRefine para la limpieza de datos sobre biodiversidad. Versión 3.0-ES." is licensed under https://creativecommons.org/licenses/by/4.0[Creative Commons Attribution 4.0 Unported License].

*_Original Language of text:_* ES, *_Original Language of figures/captions:_* ES, *_This version Language of text:_* ES, *_This version Language of figures/captions:_* ES

*_Document Control:_*
Third (GitHub) edition published, April 2019.

First published, February 2017. Authors: Paula F Zermoglio, John R Wieczorek.
