[[guía-de-uso-básico-de-openrefine]]
== Guía de Uso Básico de OpenRefine

=== Suggested citation:
Zermoglio PF, Wieczorek JR. 2019. Guía de Uso Básico de OpenRefine para la limpieza de datos sobre biodiversidad. Versión 3.0-ES. Available online at #foo. doi:xxxxxx

=== Persistent URI:
#foo

=== Authors:
Paula F Zermoglio and John Wieczorek (VertNet) are authors of original version and of this version of document.

=== Contributors:

=== License:
"Guía de Uso Básico de OpenRefine para la limpieza de datos sobre biodiversidad. Versión 3.0-ES." is licensed under https://creativecommons.org/licenses/by/4.0[Creative Commons Attribution 4.0 Unported License].

=== Original Language of text:
Spanish.

=== Original Language of figures/captions:
Spanish

=== This version Language of text:
Spanish

=== This version Language of figures/captions:
Spanish

=== Document Control:
Third (GitHub) edition published, April 2019.

First published, February 2017. Authors: Paula F Zermoglio, John R Wieczorek.
