== Prefacio

ifeval::["{lang}" != "es"]
=== Comentarios Preliminares

Las imágenes incluidas en esta Guía están en idioma castellano.
endif::[]

=== Objetivo

La presente guía ha sido construida con fines únicamente pedagógicos. El objetivo de esta guía es mostrar cómo utilizar algunas de las funciones básicas de OpenRefine que pueden utilizarse para evaluar y mejorar la calidad de datos de biodiversidad.

=== Cómo usar esta guía

En esta guía se muestra cómo utilizar funciones básicas de OpenRefine para la evaluación y mejoramiento de la calidad de un conjunto de datos de biodiversidad. Los ejemplos de uso presentados en esta guía constituyen sólo algunas de las alternativas posibles para el tratamiento de datos en OpenRefine.

Para hacer un mejor uso de esta guía, se recomienda seguir los pasos utilizando el programa OpenRefine y el conjunto de datos modelo provisto junto con este documento. Todos los ejemplos presentados corresponden a un conjunto de datos de biodiversidad que ha sido específicamente modificado por los autores.

En la Guía se utilizan los términos ‘campo’ y ‘columna’ indistintamente.

En el texto se utiliza se utiliza el siguiente formato para los [source]`"nombres de los campos originales"`.

====	Software

La versión de OpenRefine utilizada para la confección de esta guía es OpenRefine 3.3. Aunque la última versión disponible es la 3.4.1, esta ha presentado algunos problemas de memoria y por lo tanto no se aborda en esta guía.

Para ver detalles sobre cómo descargar e instalar OpenRefine en su computadora, ver el <<app-a,Apéndice 1>>.

[#datos]
====	Datos

El conjunto de datos modelo utilizado en esta guía puede obtenerse aquí: link:../data/EjercicioModelo_OpenRefine_Datos.zip[EjercicioModelo_OpenRefine_Datos.csv,opts=download]. Descargar el archivo, y no manipularlo en otros programas (e.g., MS Excel) antes de abrirlo en OpenRefine, dado que ello puede cambiar los formatos y/o codificación del archivo.

El conjunto de datos modelo fue derivado a partir del conjunto de datos: 

_Williams J (2018). Colección de Herbario. Version 3.1. Facultad de Ciencias Naturales y Museo - U.N.L.P.. Occurrence dataset https://doi.org/10.15468/i9bj5r accessed via GBIF.org on 2019-04-18._

<<<
