https://docs.gbif.org/documentation-guidelines/[image:https://docs.gbif.org/documentation-guidelines/gbif-document-shield.svg[GBIF Document]]
https://doi.org/10.15468/doc-gzjg-af18[image:https://zenodo.org/badge/DOI/10.15468/doc-gzjg-af18.svg[doi:10.15468/doc-gzjg-af18]]
https://creativecommons.org/licenses/by-sa/4.0/[image:https://img.shields.io/badge/License-CC%20BY%2D-SA%204.0-lightgrey.svg[CC BY-SA 4.0]]
https://builds.gbif.org/job/doc-openrefine-guide/[image:https://builds.gbif.org/job/doc-openrefine-guide/badge/icon[Build status]]

= Guía de Uso Básico de OpenRefine para la limpieza de datos sobre biodiversidad

La presente guía ha sido construida con fines únicamente pedagógicos. El objetivo de esta guía es mostrar cómo utilizar algunas de las funciones básicas de OpenRefine que pueden utilizarse para evaluar y mejorar la calidad de datos de biodiversidad.

_This is information *about* this document's source code.  It is not part of the document._

It is available in Spanish in both HTML and PDF at https://docs.gbif-uat.org/openrefine-guide/[Guía de Uso Básico de OpenRefine para la limpieza de datos sobre biodiversidad]. The location of these documents is currently considered temporary.

The document is built using AsciiDoc, for guidance on how to make changes or suggestions see the https://docs.gbif.org/documentation-guidelines[GBIF Documentation Guidelines].

== Syntax highlighting

The syntax highligting in this document uses a more careful syntax than normal.

----
Inline expressions are marked up like this: [source]`cells["genus"].value`.

Block expressions are marked up like this:

  [source,javascript]
  ----
  if(isBlank(cells["genus"].value),
     ""
     cells["genus"].value
  )
  ----
----

== Menus

Menus use the experimental https://asciidoctor.org/docs/user-manual/#menu-selections[menu selections] syntax.

.Inline syntax.
----
"la &#9660; azul > Facetas > Faceta de texto"
----

.Full syntax for single items and single items with spaces
----
menu:Preferencias[]
menu:la{sp}&#9660;{sp}azul[]
----

.Full syntax when including formatted text in the menu
----
// Attribute to be declared in index.es.adoc
:genus: pass:q[[source]`"genus"`]

menu:la{sp}&#9660;{sp}azul{sp}del{sp}campo{sp}{genus}[Editar columnas > Agregar columna basada en esta columna…]
----
